[general]
live_config_reload = true
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]
# import = ["~/.config/alacritty/themes/themes/one_dark.toml"]


[window]
padding = { x = 0, y = 0 }
opacity = 0.85
blur = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 10

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
  # Increase font size with Ctrl + =
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  # Decrease font size with Ctrl + -
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  # Reset font size with Ctrl + 0
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[mouse]
hide_when_typing = true
